### ISSUE TITLE
Unable to Archive to .app / No .app Released

### ISSUE THREAD

**Issue by ghost** [graphsketcher/GraphSketcher#1]
My attempts to build and archive fail. By default, the OS X version requires a code signing profile, which requires a paid developer account. Turning off code signing and attempting to build, the app crashes when run from directories other than the one in which Xcode places the build.

**Comment by graphsketcher** [comment]
There's a compiled binary on this page: https://github.com/graphsketcher/GraphSketcher/releases

**Comment by graphsketcher** [comment]
Done!

**Comment by ghost** [comment]
Thanks!
