### ISSUE TITLE
Update source for compatibility with Xcode 5.1.x toolchain and the iOS 7.1 SDK

### ISSUE THREAD

**Issue by Anzumana** [graphsketcher/GraphSketcher#10]
There seems to be some issues with building the iOS app for iOS 7.1

**Comment by RoyiAvital** [comment]
Hi,
This guy:
http://flyingbanana1024102.wordpress.com/draw-a-graph/

Created a very similar Application.

@Anzumana, Unfortunately, it seems you're the only one with programming skills interested in this project.
Why don't you approach him for collaboration?

Many people need this kind of application.

**Comment by Anzumana** [comment]
Thanks for the great suggestion.
Will do so.

**Comment by correia** [comment]
It is my intent to update the master branch so that it builds with Xcode 5.1.x and the iOS 7.1 SDK. I'm currently blocked waiting on an upstream change to the open source Omni Frameworks.

**Comment by RoyiAvital** [comment]
@Anzumana, Any luck with the new guy?

**Comment by Anzumana** [comment]
so far he has not responded. :)

**Comment by RoyiAvital** [comment]
What else could be done to attract developers?

**Comment by Anzumana** [comment]
I think the best think would be a getting started guide and stuff along those lines.
e.g.
http://openkinect.org/wiki/Main_Page

**Comment by correia** [comment]
GraphSketcher-Mac and GraphSketcher-iPad now build with Xcode 5.1 (and in the latter case, agains the iOS 7.1 SDK).

The build system issue has been resolved by the following commits:

commit 391061c6eb9680f42382a466b983a258c14c68fb
Author: Jim Correia jim.correia@pobox.com
Date:   Mon May 19 16:52:12 2014 -0700

```
Updated GraphSketcher-Mac to build with OmniInspector changes in the updated OmniGroup frameworks.
```

commit 35afc10aebf809fe6b3f5b135c06d532d655ad58
Author: Jim Correia jim.correia@pobox.com
Date:   Mon May 19 16:49:57 2014 -0700

```
Updated the linked frameworks per linkage requirements of updated OmniGroup frameworks.
```

commit d8bbb92ed32c9e369578a6a1367e9c6939da413a
Author: Jim Correia jim.correia@pobox.com
Date:   Mon May 19 16:49:05 2014 -0700

```
Updated the OmniGroup subproject to 40fbf9d1a0f565be127fc8c8ce3e665da2ea3a4e.
```

**Comment by RoyiAvital** [comment]
@correia, When can we expect to be able to download if from the App Store both for OS X and iOS? 

Thank You for your work!
