### ISSUE TITLE
Problems pasting data from spreadsheets (tab-separated values)

### ISSUE THREAD

**Issue by ncrow** [graphsketcher/GraphSketcher#13]
I am trying to paste data in from a spreadsheet.  Same behavior with either Numbers or Excel.

If I have two columns of data say 

1,1
2,2
3,3
4,4
5,7

Graphsketcher will interpret that data when pasted as:

1,11
2,22
3,33
4,44
5,57

**Comment by dmessent** [comment]
I'm seeing the same thing in Numbers. 

When you copy from Numbers, the values are placed on the pasteboard as tab-separated columns of text. It looks like GraphSketcher isn't parsing those columns and instead is interpreting them as a single column of two-digit numbers. When you paste, that column of n two-digit numbers is plotted against the integers 1 through n as described in the documentation.

Hopefully someone can take a look at this and figure out why the tabs are being mangled.
