### ISSUE TITLE
GraphSketcher 2.0 Test (v46) can't be open by users 

### ISSUE THREAD

**Issue by micheld93** [graphsketcher/GraphSketcher#15]
I tried to open the GraphSketscher.app, but my Mac tells me that the app is destroyed and should thrown to trash.

Hope you can fix this problem!

**Comment by correia** [comment]
I've replaced the binary attached to the release, and verified it after redownloading it from GitHub.

**Comment by micheld93** [comment]
Thank you very much

**Comment by RoyiAvital** [comment]
Is there out of the box running version we can try on iPad or OS X?

**Comment by correia** [comment]
Binary releases for OS X are available at https://github.com/graphsketcher/GraphSketcher/releases.

Unfortunately, there is no binary release available for the iPad at this time.
