### ISSUE TITLE
Paid copy on App Store (no credit to developers)

### ISSUE THREAD

**Issue by nkiest** [graphsketcher/GraphSketcher#16]
I saw a MacWorld piece highlighting an app that looked a lot like OmniGraph Sketcher. Upon looking closer, I would say it is identical.
https://itunes.apple.com/us/app/id893826741?mt=12
Not sure about the copyright/trademark status, but it feel really sketchy to me.

**Comment by adib** [comment]
Looking at `OmniSourceLicense.html`, GraphDraft seems legitimate as long as there's a user-visible copy of GraphSketcher's license somewhere within the app.

As for the trademark status, it doesn't use any of Omni's trademark in the App Store description nor screenshots.
