### ISSUE TITLE
Issue during iPad app build process.

### ISSUE THREAD

**Issue by EvgenyKarkan** [graphsketcher/GraphSketcher#4]
If I understand correctly - I must have Mac OS developer program App ID for build iOS app?
In my case - the iOS Dev App ID is not enough for building the iPad app. And I see an error - "The selected team doesn't have a Mac Developer Program membership".
Error occurs because of FixStringsFile Mac OS project.
So plz tell me - what am I doing wrong? 
How can I build iPad app with just only iOS Dev program account?
Thnx in advance!

**Comment by ashfurrow** [comment]
The main target depends on multiple other projects in the "Frameworks" and "Tools" folders. Select each framework, go to the "Build Settings" tab, find "Code Signing" and make sure each is set to "Don't code sign". It'd be nice if this was the default, considering many iOS developers don't have an OS X developer account. 

![screen shot 2014-01-22 at 4 11 16 pm](https://f.cloud.github.com/assets/498212/1978902/4cdddbb4-83aa-11e3-9a0f-7000c440639f.png)

**Comment by EvgenyKarkan** [comment]
Thnx Ash!
Will try ASAP.
Cheers!

**Comment by correia** [comment]
GraphSketcher depends on the OmniGroup frameworks (expressed as a submodule) and auxiliary build tools, and uses its build configurations, which sign all build products by default.

If are are not interested in building the Mac application (which must be signed because it is sandboxed), in your local copy of "Target-Mac-Common.xcconfig" change the following line:

```
// For Xcode builds, we sign our applications using our individual development certificates ("Mac Developer: [Person]"). For distribution builds, our build scripts will re-sign as "Developer ID Application: [Company]" (for direct downloads) or "3rd Party Mac Developer Application: [Company]" (for Mac App Store submissions).
OMNI_MAC_CODE_SIGN_IDENTITY = Mac Developer:
```

to

```
// For Xcode builds, we sign our applications using our individual development certificates ("Mac Developer: [Person]"). For distribution builds, our build scripts will re-sign as "Developer ID Application: [Company]" (for direct downloads) or "3rd Party Mac Developer Application: [Company]" (for Mac App Store submissions).
OMNI_MAC_CODE_SIGN_IDENTITY =
```

**Comment by EvgenyKarkan** [comment]
@correia it helps!
