### ISSUE TITLE
Getting the App into the App Store

### ISSUE THREAD

**Issue by Anzumana** [graphsketcher/GraphSketcher#9]
The Information we have to provide are : 

I will try to update when i figured out what to use where.
Here is what we know so far.

App Name: 
GraphSketcher
App Description : 
GraphSketcher is a simple, elegant tool for quickly sketching graphs and plotting data — but you don’t even need data to get started. It’s perfect for reports, presentations, and problem sets where you need to produce sharp-looking graphs on the fly.
Primary and Secondary Category : Utilities , Productivity
Subcategories: -
Copyright: ?
App Rating: 4+
Keywords: Drawing,Graph,Sketching,
SKU Number: 0001AAT
Application URL: http://www.graphsketcher.com
Screenshots:
https://www.dropbox.com/s/m6q8xl9pp6zcq1z/GraphDrawing.png
https://www.dropbox.com/s/dti2hczdeihrhk6/MyDocuments.png
https://www.dropbox.com/s/fthc5tsztae2qem/Welcome%20To%20GraphSketcher.png
Support URL: https://github.com/Anzumana/GraphSketcherSupport/issues
Support Email Address: gethelpforgraphsketcher@gmail.com
End User License Agreement: provied by apple should work right ?
Pricing, Available Date, Territories: Free, asap :)
Large App Icon 1024 x 1024:

If anyone has any suggestions  or feedback on any of those fell free :)

**Comment by Anzumana** [comment]
i created a separate repository to keep track of all the issues user have.
If there is something that needs fixing i will open the issue then here.

**Comment by Anzumana** [comment]
Itunes Record does exist now.
Binary Upload Up Next.

**Comment by RoyiAvital** [comment]
Hi,
Id din't understand, is the App available on the store?

I'd really want to use this amazing application.

**Comment by RoyiAvital** [comment]
Any updates on that?

**Comment by Anzumana** [comment]
not rly sorry

**Comment by RoyiAvital** [comment]
This is so disappointing.
This is a great applications, I was sure many would jump on the opportunity.

**Comment by RoyiAvital** [comment]
Still nothing?
We really need this guy:

https://flyingbanana1024102.wordpress.com/
